#!/bin/bash


source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

#=================================================
# RESTORE THE MYSQL DATABASE
#=================================================
ynh_script_progression "Restoring the MySQL database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

# redis
redis_db=$(ynh_redis_get_free_db)
redis_lock "$redis_db" 

celery_db=$(ynh_redis_get_free_db)
redis_lock "$celery_db"

web_db=$(ynh_redis_get_free_db)

redis_unlock "$redis_db"
redis_unlock "$celery_db"

# config 
ynh_config_add --template="pretalx.cfg" --destination="$install_dir/pretalx.cfg"
chmod 600 "$install_dir/pretalx.cfg"
chown "$app:www-data" "$install_dir/pretalx.cfg"

# log files 
mkdir -p /var/log/$app
touch /var/log/$app/pretalx.log
touch "/var/log/$app/$app-web.log"
touch "/var/log/$app/$app-worker.log"
chown -R "$app:www-data" "/var/log/$app"

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/${app}-web.service"
ynh_restore "/etc/systemd/system/${app}-worker.service"

systemctl enable "${app}-web" --quiet
systemctl enable "${app}-worker" --quiet

yunohost service add "${app}-web" --description="Conference management application" --log="/var/log/$app/$app-web.log"
yunohost service add "${app}-worker" --description="Pretalx worker" --log="/var/log/$app/$app-worker.log"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/etc/cron.d/$app"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="${app}-web" --action="start" --log_path="systemd"
ynh_systemctl --service="${app}-worker" --action="start" --log_path="systemd"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
