#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="${app}-web" --action="stop" --log_path="systemd"
ynh_systemctl --service="${app}-worker" --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

mkdir -p $install_dir

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

pushd $install_dir
#    python3 -m venv $install_dir/venv
    source "$install_dir/venv/bin/activate"
    export PATH="$PATH:$nodejs_dir" 
#    ynh_exec_as_app  $install_dir/venv/bin/pip install pip setuptools wheel gunicorn
    ynh_exec_as_app  $install_dir/venv/bin/pip install --upgrade-strategy eager -U "pretalx[postgres,redis]"
    ynh_exec_as_app  $install_dir/venv/bin/python3 -m pretalx migrate
    ynh_exec_as_app  $install_dir/venv/bin/python3 -m pretalx rebuild  --npm-install
#    ynh_exec_as_app  $install_dir/venv/bin/python3 -m pretalx updateassets
    chown -R $app:www-data "$install_dir"
    deactivate
popd

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

redis_db=$(ynh_redis_get_free_db)
redis_lock "$redis_db" 

celery_db=$(ynh_redis_get_free_db)
redis_lock "$celery_db"

web_db=$(ynh_redis_get_free_db)

redis_unlock "$redis_db"
redis_unlock "$celery_db"

ynh_config_add --template="pretalx.cfg" --destination="$install_dir/pretalx.cfg"

chmod 600 "$install_dir/pretalx.cfg"
chown "$app:$app" "$install_dir/pretalx.cfg"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}-web" --template="pretalx-web.service"
ynh_config_add_systemd --service="${app}-worker" --template="pretalx-worker.service"

yunohost service add "${app}-web" --description="Conference management application" --log="/var/log/$app/$app-web.log"
yunohost service add "${app}-worker" --description="Pretalx worker" --log="/var/log/$app/$app-worker.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="${app}-web" --action="start" --log_path="systemd"
ynh_systemctl --service="${app}-worker" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
